=== BaSysTeam/BaSYS.Examples.IssueTracker/metadata/system/schemas/metaObjectStorableSettings.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "MetaObjectStorableSettings",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string",
      "format": "guid"
    },
    "metaObjectKindUid": {
      "type": "string",
      "format": "guid"
    },
    "title": {
      "type": [
        "null",
        "string"
      ]
    },
    "name": {
      "type": [
        "null",
        "string"
      ]
    },
    "memo": {
      "type": [
        "null",
        "string"
      ]
    },
    "editMethod": {
      "$ref": "#/definitions/EditMethods"
    },
    "orderByExpression": {
      "type": [
        "null",
        "string"
      ]
    },
    "displayExpression": {
      "type": [
        "null",
        "string"
      ]
    },
    "listFormUid": {
      "type": [
        "null",
        "string"
      ],
      "format": "guid"
    },
    "itemFormUid": {
      "type": [
        "null",
        "string"
      ],
      "format": "guid"
    },
    "showMainImage": {
      "type": "boolean"
    },
    "saveHistory": {
      "$ref": "#/definitions/SaveHistoryMode"
    },
    "version": {
      "type": "integer",
      "format": "int64"
    },
    "isActive": {
      "type": "boolean"
    },
    "header": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/definitions/MetaObjectTable"
        }
      ]
    },
    "detailTables": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectTable"
      }
    },
    "commands": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectCommand"
      }
    },
    "recordsSources": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/RecordsSourceItem"
      }
    },
    "recordsSettings": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectRecordsSettingsItem"
      }
    }
  },
  "definitions": {
    "EditMethods": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Page",
        "Modal"
      ],
      "enum": [
        0,
        1
      ]
    },
    "SaveHistoryMode": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Inherit",
        "Disabled",
        "Enabled"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectTable": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "memo": {
          "type": [
            "null",
            "string"
          ]
        },
        "autoClearMethod": {
          "$ref": "#/definitions/AutoClearMethods"
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableColumn"
          }
        },
        "indexes": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableIndex"
          }
        },
        "columnsWithFormulas": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableColumn"
          }
        },
        "primaryKey": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumn"
            }
          ]
        }
      }
    },
    "AutoClearMethods": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "None",
        "WhenCopy",
        "WhenCreateFrom",
        "WhenCopyOrCreateFrom"
      ],
      "enum": [
        0,
        1,
        2,
        3
      ]
    },
    "MetaObjectTableColumn": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "kind": {
          "$ref": "#/definitions/DataObjectColumnKinds"
        },
        "standardColumnUid": {
          "type": [
            "null",
            "string"
          ],
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "formula": {
          "type": [
            "null",
            "string"
          ]
        },
        "itemsSource": {
          "type": [
            "null",
            "string"
          ]
        },
        "autoClearMethod": {
          "$ref": "#/definitions/AutoClearMethods"
        },
        "isStandard": {
          "type": "boolean"
        },
        "dataSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnDataSettings"
            }
          ]
        },
        "renderSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnRenderSettings"
            }
          ]
        },
        "validationSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnValidationSettings"
            }
          ]
        },
        "dependencies": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/DependencyInfo"
          }
        }
      }
    },
    "DataObjectColumnKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Stored",
        "Virtual"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectTableColumnDataSettings": {
      "type": "object",
      "properties": {
        "dataTypeUid": {
          "type": "string",
          "format": "guid"
        },
        "stringLength": {
          "type": "integer",
          "format": "int32"
        },
        "numberDigits": {
          "type": "integer",
          "format": "int32"
        },
        "primaryKey": {
          "type": "boolean"
        },
        "required": {
          "type": "boolean"
        },
        "unique": {
          "type": "boolean"
        },
        "defaultValue": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "MetaObjectTableColumnRenderSettings": {
      "type": "object",
      "properties": {
        "controlKindUid": {
          "type": [
            "null",
            "string"
          ]
        },
        "showInItem": {
          "type": "boolean"
        },
        "showInList": {
          "type": "boolean"
        },
        "listColumnWidth": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "MetaObjectTableColumnValidationSettings": {
      "type": "object",
      "properties": {
        "notEmpty": {
          "type": "boolean"
        }
      }
    },
    "DependencyInfo": {
      "type": "object",
      "properties": {
        "kind": {
          "$ref": "#/definitions/DependencyKinds"
        },
        "fieldUid": {
          "type": "string",
          "format": "guid"
        },
        "tableUid": {
          "type": "string",
          "format": "guid"
        }
      }
    },
    "DependencyKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "HeaderField",
        "RowField",
        "Table"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectTableIndex": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableIndexColumn"
          }
        }
      }
    },
    "MetaObjectTableIndexColumn": {
      "type": "object",
      "properties": {
        "columnUid": {
          "type": "string",
          "format": "guid"
        },
        "direction": {
          "$ref": "#/definitions/IndexDirections"
        }
      }
    },
    "IndexDirections": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Descending",
        "Ascending"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectCommand": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "tableUid": {
          "type": "string",
          "format": "guid"
        },
        "kind": {
          "$ref": "#/definitions/MetaObjectCommandKinds"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "expression": {
          "type": [
            "null",
            "string"
          ],
          "description": "JavaScript expression for this command. In export packages the value is a relative file reference (e.g. 'Catalog.Customer.command.fill_defaults.bjs') pointing to a companion .bjs file; the import pipeline resolves it back to inline code automatically.",
          "x-example": "Catalog.Customer.command.fill_defaults.bjs"
        },
        "memo": {
          "type": [
            "null",
            "string"
          ]
        },
        "isActive": {
          "type": "boolean"
        },
        "parameters": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectCommandParameter"
          }
        }
      }
    },
    "MetaObjectCommandKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Custom",
        "Fill",
        "PickUp"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectCommandParameter": {
      "type": "object",
      "properties": {
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "value": {
          "type": [
            "null",
            "string"
          ]
        },
        "dbType": {
          "$ref": "#/definitions/DbType"
        }
      }
    },
    "DbType": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "AnsiString",
        "Binary",
        "Byte",
        "Boolean",
        "Currency",
        "Date",
        "DateTime",
        "Decimal",
        "Double",
        "Guid",
        "Int16",
        "Int32",
        "Int64",
        "Object",
        "SByte",
        "Single",
        "String",
        "Time",
        "UInt16",
        "UInt32",
        "UInt64",
        "VarNumeric",
        "AnsiStringFixedLength",
        "StringFixedLength",
        "Xml",
        "DateTime2",
        "DateTimeOffset"
      ],
      "enum": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        25,
        26,
        27
      ]
    },
    "RecordsSourceItem": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "expression": {
          "type": [
            "null",
            "string"
          ],
          "description": "JavaScript expression for this records source. In export packages the value is a relative file reference (e.g. 'Catalog.Customer.records_source.main.bjs') pointing to a companion .bjs file; the import pipeline resolves it back to inline code automatically.",
          "x-example": "Catalog.Customer.records_source.main.bjs"
        }
      }
    },
    "MetaObjectRecordsSettingsItem": {
      "type": "object",
      "properties": {
        "destinationMetaObjectUid": {
          "type": "string",
          "format": "guid"
        },
        "rows": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectRecordsSettingsRow"
          }
        }
      }
    },
    "MetaObjectRecordsSettingsRow": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "sourceUid": {
          "type": "string",
          "format": "guid"
        },
        "direction": {
          "$ref": "#/definitions/RegisterRecordDirections"
        },
        "condition": {
          "type": [
            "null",
            "string"
          ]
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectRecordsSettingsColumn"
          }
        }
      }
    },
    "RegisterRecordDirections": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Plus",
        "Minus"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectRecordsSettingsColumn": {
      "type": "object",
      "properties": {
        "destinationColumnUid": {
          "type": "string",
          "format": "guid"
        },
        "expression": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    }
  }
}

=== BaSysTeam/BaSYS.Examples.IssueTracker/metadata/enum/release_status/enum.release_status.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "b03c6bce-e7c3-40df-86a3-c5897a1c6e12",
  "metaObjectKindUid": "5449a8ad-9359-41b2-8ff2-3f415eb4da76",
  "title": "Статус релиза",
  "name": "release_status",
  "memo": "Определяет этап жизненного цикла релиза.",
  "editMethod": 0,
  "orderByExpression": "",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "saveHistory": 0,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "d48243bb-b5da-4d55-bf7e-c0e02cde0e91",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "31678347-30b4-428e-b6f4-42dceed59abe",
        "kind": 0,
        "standardColumnUid": "3cceebad-7d5a-4943-a102-6267e22227a8",
        "title": "Name",
        "name": "name",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 20,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "15ba6255-f04a-4d76-aa91-36649b6c5063",
        "kind": 0,
        "standardColumnUid": "1e0063d0-288d-494a-8761-1185300d571d",
        "title": "Is deleted",
        "name": "is_deleted",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 0,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": false,
          "showInList": false,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "0aeb4c9d-e5e4-4404-89cf-7bf5caba12d1",
        "kind": 0,
        "standardColumnUid": "e647fb57-470e-4547-9a94-2be0f3d0985e",
        "title": "Code",
        "name": "code",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 3,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": true,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": true
        },
        "dependencies": []
      },
      {
        "uid": "5f73a648-4377-4107-a983-96f0ebf1e8e0",
        "kind": 0,
        "standardColumnUid": "91a26ae4-5723-4109-8322-7e4e59129239",
        "title": "Title",
        "name": "title",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": true
        },
        "dependencies": []
      }
    ],
    "indexes": [
      {
        "uid": "758d47ed-8721-4aaf-9927-5fce4d14a999",
        "columns": [
          {
            "columnUid": "15ba6255-f04a-4d76-aa91-36649b6c5063",
            "direction": 0
          }
        ]
      },
      {
        "uid": "49271d2f-2f57-4773-8409-e7d22cc0a378",
        "columns": [
          {
            "columnUid": "0aeb4c9d-e5e4-4404-89cf-7bf5caba12d1",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [],
  "recordsSources": [],
  "recordsSettings": []
}

=== BaSysTeam/BaSYS.Examples.IssueTracker/metadata/enum/urgency/enum.urgency.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "6c250d8f-c65b-43bb-84b4-7e0c8271f79d",
  "metaObjectKindUid": "5449a8ad-9359-41b2-8ff2-3f415eb4da76",
  "title": "Срочность",
  "name": "urgency",
  "memo": "Определяет требуемую скорость реакции на обращение.",
  "editMethod": 0,
  "orderByExpression": "",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "saveHistory": 0,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "086339f0-48ac-4db7-9ae2-4f762bd16bd8",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "66900b52-235a-4e62-8761-e279ac50c189",
        "kind": 0,
        "standardColumnUid": "3cceebad-7d5a-4943-a102-6267e22227a8",
        "title": "Name",
        "name": "name",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 20,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "07fc5add-bd30-41db-a23c-4f719740fb3c",
        "kind": 0,
        "standardColumnUid": "1e0063d0-288d-494a-8761-1185300d571d",
        "title": "Is deleted",
        "name": "is_deleted",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 0,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": false,
          "showInList": false,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "54c17a43-a8e8-4beb-aea8-edc612229282",
        "kind": 0,
        "standardColumnUid": "e647fb57-470e-4547-9a94-2be0f3d0985e",
        "title": "Code",
        "name": "code",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 3,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": true,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": true
        },
        "dependencies": []
      },
      {
        "uid": "2a1aaea8-11cb-44e7-bb0e-73b6c24c9ed3",
        "kind": 0,
        "standardColumnUid": "91a26ae4-5723-4109-8322-7e4e59129239",
        "title": "Title",
        "name": "title",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": true
        },
        "dependencies": []
      }
    ],
    "indexes": [
      {
        "uid": "37979c21-835b-4a24-8939-df31083da24d",
        "columns": [
          {
            "columnUid": "07fc5add-bd30-41db-a23c-4f719740fb3c",
            "direction": 0
          }
        ]
      },
      {
        "uid": "2065e56a-e027-4bb2-ba3d-bdb410624a5f",
        "columns": [
          {
            "columnUid": "54c17a43-a8e8-4beb-aea8-edc612229282",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [],
  "recordsSources": [],
  "recordsSettings": []
}

=== BaSysTeam/BaSYS.Examples.IssueTracker/metadata/enum/primevue_color/enum.primevue_color.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "77e25caf-5f94-49ba-b13c-801bc8584aff",
  "metaObjectKindUid": "5449a8ad-9359-41b2-8ff2-3f415eb4da76",
  "title": "Цвет PrimeVue",
  "name": "primevue_color",
  "memo": "Задает общий набор семантических цветов PrimeVue для оформления.",
  "editMethod": 0,
  "orderByExpression": "",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "saveHistory": 0,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "71da46c1-4e98-4aad-aad2-5965729ac5d3",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "9b9d72a9-9ebe-48e7-8083-a6705c6211cb",
        "kind": 0,
        "standardColumnUid": "3cceebad-7d5a-4943-a102-6267e22227a8",
        "title": "Name",
        "name": "name",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 20,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "22d5659b-09a1-4294-a676-5411d890da44",
        "kind": 0,
        "standardColumnUid": "1e0063d0-288d-494a-8761-1185300d571d",
        "title": "Is deleted",
        "name": "is_deleted",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 0,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": false,
          "showInList": false,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "9bb1e5bd-7e59-46e3-9748-2e00ea66d80a",
        "kind": 0,
        "standardColumnUid": "e647fb57-470e-4547-9a94-2be0f3d0985e",
        "title": "Code",
        "name": "code",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 3,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": true,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": true
        },
        "dependencies": []
      },
      {
        "uid": "7919ba9b-0256-4624-ae04-c3e2542e7ff9",
        "kind": 0,
        "standardColumnUid": "91a26ae4-5723-4109-8322-7e4e59129239",
        "title": "Title",
        "name": "title",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": true
        },
        "dependencies": []
      }
    ],
    "indexes": [
      {
        "uid": "52d25ff9-dc35-4b9f-aacb-943d8c5896d0",
        "columns": [
          {
            "columnUid": "22d5659b-09a1-4294-a676-5411d890da44",
            "direction": 0
          }
        ]
      },
      {
        "uid": "3d5b878e-49e2-47dd-b390-53277f4b21f6",
        "columns": [
          {
            "columnUid": "9bb1e5bd-7e59-46e3-9748-2e00ea66d80a",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [],
  "recordsSources": [],
  "recordsSettings": []
}
