=== BaSysTeam/BaSYS.Examples.IssueTracker/metadata/system/schemas/metaObjectStorableSettings.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "MetaObjectStorableSettings",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string",
      "format": "guid"
    },
    "metaObjectKindUid": {
      "type": "string",
      "format": "guid"
    },
    "title": {
      "type": [
        "null",
        "string"
      ]
    },
    "name": {
      "type": [
        "null",
        "string"
      ]
    },
    "memo": {
      "type": [
        "null",
        "string"
      ]
    },
    "editMethod": {
      "$ref": "#/definitions/EditMethods"
    },
    "orderByExpression": {
      "type": [
        "null",
        "string"
      ]
    },
    "displayExpression": {
      "type": [
        "null",
        "string"
      ]
    },
    "listFormUid": {
      "type": [
        "null",
        "string"
      ],
      "format": "guid"
    },
    "itemFormUid": {
      "type": [
        "null",
        "string"
      ],
      "format": "guid"
    },
    "showMainImage": {
      "type": "boolean"
    },
    "saveHistory": {
      "$ref": "#/definitions/SaveHistoryMode"
    },
    "version": {
      "type": "integer",
      "format": "int64"
    },
    "isActive": {
      "type": "boolean"
    },
    "header": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/definitions/MetaObjectTable"
        }
      ]
    },
    "detailTables": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectTable"
      }
    },
    "commands": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectCommand"
      }
    },
    "recordsSources": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/RecordsSourceItem"
      }
    },
    "recordsSettings": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/MetaObjectRecordsSettingsItem"
      }
    }
  },
  "definitions": {
    "EditMethods": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Page",
        "Modal"
      ],
      "enum": [
        0,
        1
      ]
    },
    "SaveHistoryMode": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Inherit",
        "Disabled",
        "Enabled"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectTable": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "memo": {
          "type": [
            "null",
            "string"
          ]
        },
        "autoClearMethod": {
          "$ref": "#/definitions/AutoClearMethods"
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableColumn"
          }
        },
        "indexes": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableIndex"
          }
        },
        "columnsWithFormulas": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableColumn"
          }
        },
        "primaryKey": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumn"
            }
          ]
        }
      }
    },
    "AutoClearMethods": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "None",
        "WhenCopy",
        "WhenCreateFrom",
        "WhenCopyOrCreateFrom"
      ],
      "enum": [
        0,
        1,
        2,
        3
      ]
    },
    "MetaObjectTableColumn": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "kind": {
          "$ref": "#/definitions/DataObjectColumnKinds"
        },
        "standardColumnUid": {
          "type": [
            "null",
            "string"
          ],
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "formula": {
          "type": [
            "null",
            "string"
          ]
        },
        "itemsSource": {
          "type": [
            "null",
            "string"
          ]
        },
        "autoClearMethod": {
          "$ref": "#/definitions/AutoClearMethods"
        },
        "isStandard": {
          "type": "boolean"
        },
        "dataSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnDataSettings"
            }
          ]
        },
        "renderSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnRenderSettings"
            }
          ]
        },
        "validationSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/MetaObjectTableColumnValidationSettings"
            }
          ]
        },
        "dependencies": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/DependencyInfo"
          }
        }
      }
    },
    "DataObjectColumnKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Stored",
        "Virtual"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectTableColumnDataSettings": {
      "type": "object",
      "properties": {
        "dataTypeUid": {
          "type": "string",
          "format": "guid"
        },
        "stringLength": {
          "type": "integer",
          "format": "int32"
        },
        "numberDigits": {
          "type": "integer",
          "format": "int32"
        },
        "primaryKey": {
          "type": "boolean"
        },
        "required": {
          "type": "boolean"
        },
        "unique": {
          "type": "boolean"
        },
        "defaultValue": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "MetaObjectTableColumnRenderSettings": {
      "type": "object",
      "properties": {
        "controlKindUid": {
          "type": [
            "null",
            "string"
          ]
        },
        "showInItem": {
          "type": "boolean"
        },
        "showInList": {
          "type": "boolean"
        },
        "listColumnWidth": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "MetaObjectTableColumnValidationSettings": {
      "type": "object",
      "properties": {
        "notEmpty": {
          "type": "boolean"
        }
      }
    },
    "DependencyInfo": {
      "type": "object",
      "properties": {
        "kind": {
          "$ref": "#/definitions/DependencyKinds"
        },
        "fieldUid": {
          "type": "string",
          "format": "guid"
        },
        "tableUid": {
          "type": "string",
          "format": "guid"
        }
      }
    },
    "DependencyKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "HeaderField",
        "RowField",
        "Table"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectTableIndex": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectTableIndexColumn"
          }
        }
      }
    },
    "MetaObjectTableIndexColumn": {
      "type": "object",
      "properties": {
        "columnUid": {
          "type": "string",
          "format": "guid"
        },
        "direction": {
          "$ref": "#/definitions/IndexDirections"
        }
      }
    },
    "IndexDirections": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Descending",
        "Ascending"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectCommand": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "tableUid": {
          "type": "string",
          "format": "guid"
        },
        "kind": {
          "$ref": "#/definitions/MetaObjectCommandKinds"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "expression": {
          "type": [
            "null",
            "string"
          ],
          "description": "JavaScript expression for this command. In export packages the value is a relative file reference (e.g. 'Catalog.Customer.command.fill_defaults.bjs') pointing to a companion .bjs file; the import pipeline resolves it back to inline code automatically.",
          "x-example": "Catalog.Customer.command.fill_defaults.bjs"
        },
        "memo": {
          "type": [
            "null",
            "string"
          ]
        },
        "isActive": {
          "type": "boolean"
        },
        "parameters": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectCommandParameter"
          }
        }
      }
    },
    "MetaObjectCommandKinds": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Custom",
        "Fill",
        "PickUp"
      ],
      "enum": [
        0,
        1,
        2
      ]
    },
    "MetaObjectCommandParameter": {
      "type": "object",
      "properties": {
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "value": {
          "type": [
            "null",
            "string"
          ]
        },
        "dbType": {
          "$ref": "#/definitions/DbType"
        }
      }
    },
    "DbType": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "AnsiString",
        "Binary",
        "Byte",
        "Boolean",
        "Currency",
        "Date",
        "DateTime",
        "Decimal",
        "Double",
        "Guid",
        "Int16",
        "Int32",
        "Int64",
        "Object",
        "SByte",
        "Single",
        "String",
        "Time",
        "UInt16",
        "UInt32",
        "UInt64",
        "VarNumeric",
        "AnsiStringFixedLength",
        "StringFixedLength",
        "Xml",
        "DateTime2",
        "DateTimeOffset"
      ],
      "enum": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        25,
        26,
        27
      ]
    },
    "RecordsSourceItem": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "title": {
          "type": [
            "null",
            "string"
          ]
        },
        "expression": {
          "type": [
            "null",
            "string"
          ],
          "description": "JavaScript expression for this records source. In export packages the value is a relative file reference (e.g. 'Catalog.Customer.records_source.main.bjs') pointing to a companion .bjs file; the import pipeline resolves it back to inline code automatically.",
          "x-example": "Catalog.Customer.records_source.main.bjs"
        }
      }
    },
    "MetaObjectRecordsSettingsItem": {
      "type": "object",
      "properties": {
        "destinationMetaObjectUid": {
          "type": "string",
          "format": "guid"
        },
        "rows": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectRecordsSettingsRow"
          }
        }
      }
    },
    "MetaObjectRecordsSettingsRow": {
      "type": "object",
      "properties": {
        "uid": {
          "type": "string",
          "format": "guid"
        },
        "sourceUid": {
          "type": "string",
          "format": "guid"
        },
        "direction": {
          "$ref": "#/definitions/RegisterRecordDirections"
        },
        "condition": {
          "type": [
            "null",
            "string"
          ]
        },
        "columns": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/MetaObjectRecordsSettingsColumn"
          }
        }
      }
    },
    "RegisterRecordDirections": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Plus",
        "Minus"
      ],
      "enum": [
        0,
        1
      ]
    },
    "MetaObjectRecordsSettingsColumn": {
      "type": "object",
      "properties": {
        "destinationColumnUid": {
          "type": "string",
          "format": "guid"
        },
        "expression": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    }
  }
}

=== BaSysTeam/BaSYS.Examples.IssueTracker/metadata/catalog/release/catalog.release.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "59a10456-44a4-4fb5-b60e-d45c6510af67",
  "metaObjectKindUid": "032d8377-500f-4631-b435-1f7f69046674",
  "title": "Релиз",
  "name": "release",
  "memo": "Хранит версии продукта, плановые и фактические даты публикации и описание изменений.",
  "editMethod": 0,
  "orderByExpression": "",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "saveHistory": 0,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "91c6f6b8-154a-404b-bc92-162add1fb8dc",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "72becdb8-0961-4f5c-bf50-545f00f49d43",
        "kind": 0,
        "standardColumnUid": "4a7c739c-6012-4e45-bfc0-b78a06db8aec",
        "title": "Id",
        "name": "id",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "b327f82a-ea96-416f-9836-785db28eccac",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "a2af0416-e8a2-411f-b858-b380bf6cea89",
        "kind": 0,
        "standardColumnUid": "b20fcd24-ba0f-b5b8-7e4d-39628145533e",
        "title": "Uid",
        "name": "uid",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "6fa9c45b-f514-4fea-a480-8e940636a1df",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": true,
          "defaultValue": "new"
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": false,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "d7de2dfb-3ca8-44e9-add6-25751fd349c9",
        "kind": 0,
        "standardColumnUid": "dc3def1b-bffd-4dc8-b0d5-5d34a57fdcb2",
        "title": "Удалено",
        "name": "is_deleted",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": false,
          "showInList": false,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "9aadf82a-e2a5-47a0-840b-4eab0193f77e",
        "kind": 0,
        "standardColumnUid": "e163c0c4-de77-4e58-a468-f3527b573e4a",
        "title": "Заголовок",
        "name": "title",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": true
        },
        "dependencies": []
      },
      {
        "uid": "d3152a48-462c-4e88-884c-85ea40471ce5",
        "kind": 0,
        "standardColumnUid": "349f72d7-ac0f-40cd-b02d-a5b5f7dcd467",
        "title": "Файлы",
        "name": "is_files",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "4bff64cf-eb01-4933-9f3d-b902336751f4",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": false,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "218f1f9c-404d-41ab-8e58-62c210e6b02c",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Статус",
        "name": "status",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "b03c6bce-e7c3-40df-86a3-c5897a1c6e12",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": true
        },
        "dependencies": []
      },
      {
        "uid": "211c1a26-17d8-48f3-a7f6-d2909085bb12",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Плановая дата публикации",
        "name": "planned_date",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "9001eafb-efb1-442f-b288-723bb8002b12",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "6704b8b6-7629-44f5-9924-963ce9a6fe9d",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Дата публикации",
        "name": "published_at",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "9001eafb-efb1-442f-b288-723bb8002b12",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "1fd79fef-400a-4ec6-b0dd-83edede149f3",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Описание изменений",
        "name": "description",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 4000,
          "numberDigits": 2,
          "primaryKey": false,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      }
    ],
    "indexes": [
      {
        "uid": "e0d20e27-738b-4710-9816-7c53e54488de",
        "columns": [
          {
            "columnUid": "d7de2dfb-3ca8-44e9-add6-25751fd349c9",
            "direction": 0
          }
        ]
      },
      {
        "uid": "31ab22d5-7c0e-401a-8743-b96840efd735",
        "columns": [
          {
            "columnUid": "d3152a48-462c-4e88-884c-85ea40471ce5",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [],
  "recordsSources": [],
  "recordsSettings": []
}

=== BaSysTeam/BaSYS.Examples.IssueTracker/metadata/register/discussion_message/register.discussion_message.json
{
  "$schema": "../../system/schemas/metaObjectStorableSettings.schema.json",
  "uid": "953c897a-1c23-40ae-bed9-6b6794f855d6",
  "metaObjectKindUid": "f3ecb444-8e72-4387-83f1-66c712de1c32",
  "title": "Сообщение обсуждения",
  "name": "discussion_message",
  "memo": "Хранит переписку по обращениям.",
  "editMethod": 0,
  "orderByExpression": "created_at",
  "displayExpression": "",
  "listFormUid": null,
  "itemFormUid": null,
  "showMainImage": false,
  "saveHistory": 0,
  "version": 0,
  "isActive": true,
  "header": {
    "uid": "b821ea89-d71c-4c5e-8404-a8ddeabc478c",
    "title": "header",
    "name": "header",
    "memo": "",
    "autoClearMethod": 0,
    "columns": [
      {
        "uid": "317b3198-271f-416d-81ea-b34ee9a72d98",
        "kind": 0,
        "standardColumnUid": "96b5f50b-98de-43fb-aea5-70fc29a35763",
        "title": "Id",
        "name": "id",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": true,
        "dataSettings": {
          "dataTypeUid": "daa57cb0-32eb-4709-b61f-4ea023ae31c3",
          "stringLength": 0,
          "numberDigits": 2,
          "primaryKey": true,
          "required": false,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "66a631db-e3cb-4bb5-9387-8b181b64c26f",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Обращение",
        "name": "issue",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "16aa4a9e-358d-4c3a-a0ec-a13e6be22ab2",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "8dd7c595-996d-49c1-8bda-d432c2f3faf3",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Дата и время",
        "name": "created_at",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "9001eafb-efb1-442f-b288-723bb8002b12",
          "stringLength": 0,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "cd4dfccd-09d3-4745-8719-329383e7656a",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Автор",
        "name": "author",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "a964c3a2-3846-4f93-93e8-ea0c15952508",
          "stringLength": 100,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      },
      {
        "uid": "99ad8da9-22f5-4867-9137-e3f742fb70ab",
        "kind": 0,
        "standardColumnUid": null,
        "title": "Сообщение",
        "name": "text",
        "formula": "",
        "itemsSource": "",
        "autoClearMethod": 0,
        "isStandard": false,
        "dataSettings": {
          "dataTypeUid": "0234c067-7868-46b2-ba8e-e22fae5255cb",
          "stringLength": 4000,
          "numberDigits": 2,
          "primaryKey": false,
          "required": true,
          "unique": false,
          "defaultValue": null
        },
        "renderSettings": {
          "controlKindUid": "",
          "showInItem": true,
          "showInList": true,
          "listColumnWidth": ""
        },
        "validationSettings": {
          "notEmpty": false
        },
        "dependencies": []
      }
    ],
    "indexes": [
      {
        "uid": "625b3987-6f1c-4944-8a17-097d2a62b44a",
        "columns": [
          {
            "columnUid": "66a631db-e3cb-4bb5-9387-8b181b64c26f",
            "direction": 0
          },
          {
            "columnUid": "8dd7c595-996d-49c1-8bda-d432c2f3faf3",
            "direction": 0
          }
        ]
      }
    ]
  },
  "detailTables": [],
  "commands": [],
  "recordsSources": [],
  "recordsSettings": []
}
